os:
  - linux
  - windows

language: rust

cache: cargo

rust:
  - 1.27.0
  - stable

script:
  - cargo check --all-targets --features strict
  - cargo test

matrix:
  include:
    - rust: nightly
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo check --all-targets --features strict
        - cargo test
        - cargo fmt -- --check
        - cargo rustdoc -- --deny warnings
