[package]
name = "rlbot"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
description = "RLBot bindings for Rust"
documentation = "https://docs.rs/rlbot/"
repository = "https://github.com/whatisaphone/rlbot-rust"
readme = "README-crates-io.md"
keywords = ["rlbot", "rocket-league", "game"]
license = "MIT"

[badges]
travis-ci = { repository = "whatisaphone/rlbot-rust" }

[dependencies]
libloading = "0.5.0"
ratelimit = "0.4.3"
flatbuffers = "0.4.0"

[dev-dependencies]
nalgebra = "0.16.0"
winapi = { version = "0.3.5", features = ["synchapi"] }
winproc = "0.5.1"

[features]
strict = []
